-- ============================================
-- games 表：游戏列表（在 Supabase SQL Editor 中执行）
-- ============================================

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category text not null default '其他',
  type text not null default '其他',
  cover_url text,
  bv_id text,
  link text,
  status text not null default '开发中',
  tech_stack text[] default '{}',
  features text[] default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 若已执行过旧版建表，补充 link 列
alter table public.games add column if not exists link text;

-- 开启行级安全并允许匿名读取
alter table public.games enable row level security;

drop policy if exists "games_public_select" on public.games;
create policy "games_public_select" on public.games
  for select using (true);

-- 种子数据
insert into public.games (title, description, category, type, cover_url, bv_id, status, tech_stack, features) values
(
  '3D 横版动作冒险游戏',
  '自学 Unity 独立开发，参考《血污：夜之仪式》制作 3D 横版闯关冒险游戏，包含背包、任务、战斗、商店、剧情对话等完整系统。',
  '自研游戏',
  '动作冒险',
  null,
  'BV114wkzQEU6',
  '已完成',
  '{Unity,C#,Input System,状态机,UGUI,对象池}',
  '{"完整游戏系统：背包、任务、战斗、商店、剧情对话","Input System 处理输入，状态机管理移动/跳跃/冲刺/攻击","对象池管理子弹特效，UGUI 无限滚动列表","Json 本地存储游戏配置数据","Animator Controller + 动画事件驱动角色动画"}'
),
(
  '抽卡模拟器',
  '纯原生 JS 自主编写完整抽卡核心逻辑，CSS 完成页面视觉美化与交互样式，Vue2 生命周期钩子管理页面状态。',
  'Web 项目',
  '卡牌抽卡',
  null,
  null,
  '已完成',
  '{HTML5,CSS3,JavaScript,Vue2}',
  '{"原生 JS 抽卡概率核心逻辑","CSS3 视觉与交互动效","Vue2 生命周期状态管理"}'
);
