-- ============================================
-- tools 表：工具列表（在 Supabase SQL Editor 中执行）
-- ============================================

create table if not exists public.tools (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category text not null default '其他',
  type text not null default '其他',
  link text,
  deploy_url text,
  cover_url text,
  status text not null default '可用',
  tech_stack text[] default '{}',
  features text[] default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 若已执行过旧版建表，补充 deploy_url 列
alter table public.tools add column if not exists deploy_url text;
alter table public.tools add column if not exists cover_url text;

-- 开启行级安全并允许匿名读取
alter table public.tools enable row level security;

drop policy if exists "tools_public_select" on public.tools;
create policy "tools_public_select" on public.tools
  for select using (true);

-- 种子数据
insert into public.tools (title, description, category, type, link, deploy_url, status, tech_stack, features) values
(
  'SuQCanvas',
  '一款基于浏览器的无限画布应用。把图片、视频、音频、PDF、Markdown、文本等各类文件拖到同一张画布上，用连线组织它们的关系，并自动保存在本地。',
  '设计工具',
  '在线画布',
  'https://github.com/suqi-bot/SuQCanvas',
  'http://116.62.113.32/SuQCanvas/',
  '可用',
  '{React,TypeScript,Vite,Tailwind CSS,Zustand,Dexie}',
  '{"无限画布：滚轮缩放、中键拖动、左键框选","多媒体元素：图片 / 视频 / 音频 / PDF / Markdown / 文本","连线系统：实线 / 虚线 / 曲线 / 箭头等多样式","IndexedDB 自动保存与多项目管理","一键导出 .sqcanvas 项目文件，可导入还原","深色 / 白色主题一键切换"}'
),
(
  '超级图片管理大师',
  '一款基于规则的桌面端图片合规管理工具，通过自动化命名、尺寸、格式和 DPI 校验，帮助你对图片资产进行规范化整理与质量管控。',
  '效率工具',
  '桌面应用',
  'https://github.com/suqi-bot/Super_SuQ_Image_Alignment_Tool',
  null,
  '可用',
  '{Python,PyQt6,Pillow}',
  '{"规则预设：命名模板、格式、大小、尺寸、DPI 约束","拖拽导入 + 智能命名 + 自动归档","一键合规检测：五维校验并归档到 Incorrect/","修复后自动恢复 + 违规原因追踪","批量导入 / 批量重命名 / 批量删除","规则导入导出与规则库共享"}'
);
